// Ícones favoritos do IconSelect — aparecem primeiro no dropdown, antes do
// separador. O resto segue a ordem do JSON do pacote (= ordem dos IDs da
// tabela `bootstrap_icons`).
//
// Formato: nome do ícone sem o prefixo `bi-` (ex.: 'arrow-down-left-circle-fill').
// Nomes inexistentes são ignorados. A ordem aqui é a ordem de exibição.
//
// Espelho de `bootstrap_icons.is_favorite = 1`. Ponto de troca futuro: quando a
// tabela tiver endpoint, esta lista passa a vir do banco.

export const ICON_FAVORITOS: readonly string[] = [
  // Pessoa / identificação
  'person',
  'person-fill',
  'person-circle',
  'person-vcard',
  'person-badge',
  'person-lines-fill',
  'person-rolodex',
  'people',
  'people-fill',
  'person-plus',
  // Empresa / PJ
  'building',
  'buildings',
  'briefcase',
  'bank',
  // Contato
  'telephone',
  'telephone-fill',
  'envelope',
  'envelope-at',
  'chat-dots',
  'chat-left-text',
  'whatsapp',
  'at',
  'headset',
  // Endereço
  'geo-alt',
  'geo-alt-fill',
  'house',
  'house-door',
  'map',
  'pin-map',
  'signpost-2',
  'globe',
  // Documentos
  'file-earmark-text',
  'file-earmark-person',
  'card-list',
  'card-text',
  'folder',
  'paperclip',
  // Financeiro
  'credit-card',
  'cash-stack',
  'wallet2',
  'currency-dollar',
  'receipt',
  'piggy-bank',
  // Datas
  'calendar-event',
  'calendar-date',
  'clock-history',
  // Config / observações
  'gear',
  'sliders',
  'journal-text',
  'sticky',
  'pencil-square',
  // Marcadores / status
  'tag',
  'tags',
  'bookmark-star',
  'flag',
  'star',
  'check-circle',
  'patch-check',
  // Acesso
  'key',
  'lock',
  'shield-lock',
  'person-lock',
  // Extras
  'list-check',
  // Pet / veterinária — identificação
  'heart',
  'card-heading',
  'bookmark',
  'palette',
  'upc-scan',
  'qr-code',
  'camera',
  'image',
  // Pet / veterinária — saúde e prontuário
  'heart-pulse',
  'activity',
  'clipboard-pulse',
  'clipboard2-pulse',
  'clipboard-heart',
  'file-medical',
  'file-earmark-medical',
  'hospital',
  'thermometer-half',
  'droplet',
  'eyedropper',
  'bandaid',
  // Pet / veterinária — medicação
  'capsule',
  'capsule-pill',
  'prescription',
  'prescription2',
  'shield-plus',
  // Pet / veterinária — procedimento e medidas
  'scissors',
  'speedometer2',
  'rulers',
  'graph-up',
  // Pet / veterinária — alimentação
  'cup-straw',
  'egg-fried',
  'basket',
  'basket2',
  // Pet / veterinária — agenda
  'calendar2-heart',
  'calendar-plus',
  'calendar-check',
  'calendar2-week',
  'clock',
  // Pet / veterinária — parasitas e alerta
  'bug',
  'exclamation-triangle',
  'exclamation-circle',
  // Agenda de compromissos — lembrete / alarme
  'bell',
  'bell-fill',
  'alarm',
  'alarm-fill',
  'stopwatch',
  // Agenda de compromissos — recorrência
  'arrow-repeat',
  'arrow-clockwise',
  // Agenda de compromissos — duração / espera
  'hourglass-split',
  'hourglass',
  // Agenda de compromissos — reunião online
  'camera-video',
  'camera-video-fill',
  'link-45deg',
  'box-arrow-up-right',
  // Agenda de compromissos — local / sala
  'door-open',
  'door-closed',
  'easel',
  'display',
  'geo',
  // Agenda de compromissos — visões de calendário
  'calendar-week',
  'calendar-month',
  'calendar3',
  'calendar-range',
  'calendar4-week',
  // Agenda de compromissos — participantes / confirmação
  'person-check',
  'person-x',
  'check2-circle',
  'x-circle',
  // Agenda de compromissos — pauta / tarefas
  'list-task',
  'card-checklist',
  // Mapa / endereço — pin e marcador
  'pin',
  'pin-fill',
  'pin-angle',
  'pin-angle-fill',
  'pin-map-fill',
  'geo-fill',
  // Mapa / endereço — mapa e navegação
  'map-fill',
  'compass',
  'compass-fill',
  'crosshair',
  'crosshair2',
  'bullseye',
  // Mapa / endereço — placas e rotas
  'signpost',
  'signpost-fill',
  'signpost-split',
  'signpost-split-fill',
  'signpost-2-fill',
  // Mapa / endereço — globo e região
  'globe2',
  'globe-americas',
  'globe-europe-africa',
  // Mapa / endereço — imóvel e residência
  'house-fill',
  'house-door-fill',
  'houses',
  'house-add',
  'house-gear',
  'house-heart',
  'building-fill',
  // Mapa / endereço — correspondência
  'mailbox',
  'mailbox2',
  'postcard',
  'postage',
  // Mensageria / contatos — chat e mensagens
  'chat',
  'chat-fill',
  'chat-left-dots',
  'chat-right-text',
  'chat-square-text',
  'chat-text',
  'chat-quote',
  'chat-heart',
  // Mensageria / contatos — envio e caixa
  'send',
  'send-fill',
  'send-check',
  'envelope-fill',
  'envelope-open',
  'envelope-plus',
  'inbox',
  'inboxes',
  'archive',
  'reply',
  'reply-all',
  // Mensageria / contatos — difusão
  'megaphone',
  'megaphone-fill',
  'broadcast',
  'broadcast-pin',
  // Mensageria / contatos — telefonia e agenda
  'person-vcard-fill',
  'telephone-inbound',
  'telephone-outbound',
  'telephone-plus',
  'telephone-forward',
  'phone',
  'journal',
  'book',
  // Mensageria / contatos — grupos
  'person-workspace',
  'diagram-3',
  'diagram-3-fill',
  'collection',
  'person-badge-fill',
  // Mensageria / contatos — bloqueio e silenciar
  'person-dash',
  'person-dash-fill',
  'person-fill-slash',
  'bell-slash',
  'bell-slash-fill',
  'shield-slash',
  'shield-x',
  'mic-mute',
  'volume-mute',
  'eye-slash',
  'x-octagon',
  'sign-stop',
  'slash-circle',
  'dash-circle',
];
