// Barrel dos services da v1. Import unico:  import { userManagerView } from '@/services/v1';

export { authService } from './auth.service';
export { userManagerTable } from './userManager.table';
export { userManagerView } from './userManager.view';
export { userRolesTable } from './userRoles.table';
export { uploadManagerTable } from './uploadManager.table';
export { uploadManagerView } from './uploadManager.view';
export { uploadManagerUpload } from './uploadManager.upload';
export { formManagerTable } from './formManager.table';
export { formManagerView } from './formManager.view';
export { formGroupsTable } from './formGroups.table';
export { formRowsTable } from './formRows.table';
export { formCamposTable } from './formCampos.table';
export { listManagerTable } from './listManager.table';
export { listColumnsTable } from './listColumns.table';
export { listActionsTable } from './listActions.table';
export { navManagerTable } from './navManager.table';
export { menuManagerTable } from './menuManager.table';
export { dbSchema } from './dbSchema';
